site_name: Forge Networking Remastered
pages:
    - Home:
        - index.md
        - authoritative-design.md
    - Getting Started:
        - getting-started.md
        - basic-moving-cube-example.md
        - basic-rpc-example.md
        - basic-instantiation-example.md
        - jump-start-guide.md
#       - Game Lobby Example
    - Network Contract Wizard (NCW):
        - network-contract-wizard-ncw.md
        - extending-generated-classes.md
        - name-collision-issues.md
    - Network Object:
        - changing-ownership.md
        - destroying-the-network-object.md
        - fields.md
        - Remote Procedure Calls (RPCs):
            - remote-procedure-calls.md
            - buffered-rpcs.md
            - sending-rpc-to-a-single-player.md
            - rpcargs-and-rpcinfo-structs.md
            - rpc-validation-by-server.md
            - replacing-previous-buffered-rpcs.md
            - clearing-buffered-rpcs.md
    - Unity Integration:
        - gameobject-execution-order.md
#        - Network Manager
        - network-instantiation.md
#        - Network Object Without Prefab
        - threading-in-unity.md
        - main-threading-rpcs.md
        - running-unity-specific-code-on-the-main-thread.md
    - Basic Network Setup Samples:
        - server-hosting-code.md
        - client-connecting-code.md
    - Events:
        - connection-cycle-events.md
    - Scene Navigation:
        - loading-scenes.md
        - scene-events.md
    - Rewinding: rewinding.md
    - Master Server:
        - master-server-quick-start.md
        - connecting-to-master-server.md
        - getting-host-list-from-master-server.md
        - windows-server-firewall-setup.md
#        - Matchmaking
    - Debugging:
        - network-logging.md
    - NetWorker:
#        - NetworkingPlayer
        - temporarily-blocking-connections.md
        - thread-safe-player-iteration.md
    - NAT Hole Punching: nat-hole-punching.md
    - Working With Multiple Sockets: working-with-multiple-sockets.md
    - LAN Discovery: lan-discovery.md
    - Troubleshooting:
        - troubleshooting.md
        - throttling-network-internal.md
    - Offline Mode: offline-mode.md
    - Lobby System: lobby.md
    - Contributing:
        - adding-and-updating-docs.md
theme: readthedocs

markdown_extensions:
    - pyembed.markdown